### ISSUE TITLE
project setup/scaffolding

### ISSUE THREAD

**Issue by snowbytes** [snowbytes/blog-engine#16]
In no particular order:
- [x] add readme/license (#25)
- [ ] configure build tools (#17)
- [ ] add stack libraries (#26)
- [ ] add testing libraries (#27)
- [ ] create folder structure (#28)
- [ ] init the project (#29)
- [ ] setup docker (#32)
- [ ] configure CI (#30)
- [ ] configure CD (#31)
